wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.6
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 3
      4: 3.7.6
      5: 0.10.15
batch_size:
  desc: null
  value: 128
clip:
  desc: null
  value: 5
dropout:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 1
ffnn_layers:
  desc: null
  value: 1
hidden_dim:
  desc: null
  value: 512
lr:
  desc: null
  value: 7.0e-05
lstm_layers:
  desc: null
  value: 2
one_cycle:
  desc: null
  value: true
output_weeks:
  desc: null
  value: 6
shuffle:
  desc: null
  value: true
use_past:
  desc: null
  value: true
use_previous_year:
  desc: null
  value: false
use_season:
  desc: null
  value: true
use_static:
  desc: null
  value: false
